// Generated by tools/symbols.py from re/symbols.toml - do not edit.
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.symbol.SourceType;

public class ApplySymbols extends GhidraScript {
    void name(long v, String n, boolean isFn) throws Exception {
        Address a = currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(v);
        if (isFn) {
            disassemble(a);
            Function f = getFunctionContaining(a);
            if (f == null) f = createFunction(a, n);
            if (f != null) { f.setName(n, SourceType.USER_DEFINED); return; }
        }
        createLabel(a, n, true);
    }

    public void run() throws Exception {
        name(0x4000704eL, "track_to_voice", true);
        name(0x40008a0eL, "pattern_track_load", true);
        name(0x40008baaL, "pattern_track_load_euclid_resume", false);
        name(0x40008ca8L, "pattern_track_save", true);
        name(0x40008e48L, "pattern_track_save_euclid_resume", false);
        name(0x40033438L, "kit_param_changed", true);
        name(0x400376d4L, "param_apply_delta", true);
        name(0x400376dcL, "param_apply_delta_resume", false);
        name(0x400376e4L, "param_apply_delta_body", false);
        name(0x400376eaL, "param_apply_delta_track", false);
        name(0x400381a0L, "page_get_value", true);
        name(0x400381a8L, "page_get_value_body", false);
        name(0x4006e1caL, "bitmap_ctor", true);
        name(0x40076c14L, "view_invalidate", true);
        name(0x4008022eL, "is_key_held", true);
        name(0x400989d0L, "trig_fire", true);
        name(0x40098ae6L, "trig_fire_euclid_flag_resume", false);
        name(0x40098ba0L, "trig_fire_flags_join", false);
        name(0x40098fbaL, "trig_fire_vel_resume", false);
        name(0x400a3d08L, "kit_track_sound", true);
        name(0x400a58f8L, "param_value_text", true);
        name(0x400a5900L, "param_value_text_resume", false);
        name(0x400a5908L, "param_value_text_body", false);
        name(0x400a5910L, "param_value_text_args", false);
        name(0x400a5aceL, "getbyid_vel_jsr", false);
        name(0x400a5b64L, "getbyid_boolop_jsr", false);
        name(0x400a62b4L, "param_short_name_body", false);
        name(0x400a6fc0L, "setbyid_boolop_jsr", false);
        name(0x400ac2e8L, "current_track_pattern", true);
        name(0x400b3a04L, "track_index_of", true);
        name(0x400bcdb4L, "vel_get_stock", true);
        name(0x400bcfa6L, "pattern_step_has_trig", true);
        name(0x400bd54cL, "pattern_length", true);
        name(0x400bde96L, "euclid_enabled_get", true);
        name(0x400bdec6L, "euclid_enabled_set", true);
        name(0x400be244L, "euclid_bool_op_get", true);
        name(0x400be274L, "euclid_bool_op_set", true);
        name(0x400be2d6L, "euclid_step_map_get", true);
        name(0x400bea2cL, "euclid_generate", true);
        name(0x400bf4aaL, "trig_flags_set", true);
        name(0x400c0ca2L, "euclid_bake", true);
        name(0x400c0caaL, "euclid_bake_body", false);
        name(0x400c71d2L, "filter_view_page_count", false);
        name(0x400c71d8L, "filter_view_page_list", false);
        name(0x400f859cL, "euclid_bool_op_format", true);
        name(0x400f8634L, "boolop_icon_draw", true);
        name(0x400f8718L, "param_info", true);
        name(0x400f8722L, "param_info_resume", false);
        name(0x400f8736L, "page_info", true);
        name(0x400f873cL, "page_info_resume", false);
        name(0x4010795eL, "voice_out", true);
        name(0x401189e8L, "voice_out_call_a", false);
        name(0x40119d8aL, "voice_out_call_b", false);
        name(0x4011cbe2L, "boolop_iconset_jsr", false);
        name(0x4013d9d8L, "param_text_format", true);
        name(0x401556ccL, "project_singleton", true);
        name(0x401737a2L, "sound_get", true);
        name(0x40186632L, "bitmap_set_make", true);
        name(0x4018e004L, "PARAM_ROM", false);
        name(0x401ae368L, "EUCLID_CHANGE_INFO", false);
        name(0x401b96d0L, "euclid_bool_op_labels", false);
        name(0x40209f2fL, "LBL_SUB", false);
        name(0x4020af96L, "LBL_OR", false);
        name(0x40210b79L, "LBL_AND", false);
        name(0x4022071eL, "LBL_XOR", false);
        name(0x40254e2cL, "voice_owner", false);
        name(0x416a6aa4L, "PARAM_INFO_BASE", false);
        name(0x416c6d90L, "boolop_icon_set", false);
        name(0x416c70c0L, "project_instance", false);
        println("applied 69 symbols");
    }
}
