#!/usr/bin/env python3
"""Generate mods/0008-sample-cut/tables.inc: the cutoff tables for the CUT page.

64 cutoff steps, log-spaced from 20 Hz to 20 kHz (a step is 10 octaves / 63, about
1.9 semitones). The knob's 0..127 maps to a step as value >> 1.

For each step, the coefficients of a trapezoidal (zero-delay) state-variable filter,
Butterworth (k = sqrt 2), at fs = 48 kHz - the Rytm's audio rate (1500 interrupts a
second, 32 samples each):

    g  = tan(pi * fc / fs)
    a1 = 1 / (1 + g * (g + k))
    a2 = g * a1
    a3 = g * a2

Only a1 (Q31) and g (Q28, g < 3.8) are stored, 8 bytes a step; the stub derives
a2 = g * a1 and a3 = g * a2 once per block on the EMAC (Q28 x Q31 -> Q28, << 3).
tools/sim_cut.py models exactly that derivation.

Also written: the popup's frequencies. Step i is 20 Hz * 10^(i/21), so they are 21
mantissas in tenths of a Hz (200 .. 1788) and a power of ten (i / 21): 42 bytes
instead of a 64-entry table.

    python3 tools/gen_cut_tables.py          # write
    python3 tools/gen_cut_tables.py --check  # fail if the file is out of date
"""
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "mods" / "0008-sample-cut" / "tables.inc"
FS = 48000.0
K = math.sqrt(2.0)
STEPS = 64


def q31(x: float) -> int:
    v = int(round(x * 2**31))
    return max(0, min(v, 0x7FFFFFFF))


def fc_of(i: int) -> float:
    return 20.0 * 1000.0 ** (i / (STEPS - 1))       # = 20 * 10^(i/21)


def render() -> str:
    lines = ["| Generated by tools/gen_cut_tables.py - do not edit.",
             f"| {STEPS} steps, 20 Hz .. 20 kHz, fs {FS:.0f}, Butterworth SVF (k = sqrt 2).",
             "| Per step: a1 (Q31), g (Q28).", "",
             "        .align  2", "cut_coef:"]
    for i in range(STEPS):
        fc = fc_of(i)
        g = math.tan(math.pi * fc / FS)
        a1 = 1.0 / (1.0 + g * (g + K))
        lines.append(f"        .long   0x{q31(a1):08x}, 0x{int(round(g * 2**28)):08x}"
                     f"   | {i:2d}: {fc:8.1f} Hz")
    mant = [int(round(fc_of(j) * 10)) for j in range(21)]
    lines += ["", "        .align  2", "cut_mant:                               | tenths of a Hz, steps 0..20"]
    for j in range(0, 21, 7):
        lines.append("        .short  " + ", ".join(str(m) for m in mant[j:j + 7]))
    return "\n".join(lines) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            raise SystemExit(f"{OUT.relative_to(ROOT)} is out of date: run tools/gen_cut_tables.py")
        print("tables.inc current")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
