"""Load re/symbols.toml and render it for the assembler and for Ghidra."""

import tomllib
from pathlib import Path

KINDS = ("fn", "data", "const")

# Both outputs describe MAIN OS: build/symbols.inc is included by the stubs and
# ApplySymbols.java annotates the MAIN OS Ghidra project. Entries for anything else
# stay in the TOML as documentation and are emitted nowhere:
#   "bootstrap"  a separate image at its own load base (0x07020000)
#   "hardware"   a memory-mapped register, outside any loaded image - emitting it
#                would make ApplySymbols try to label an address Ghidra has not got
IMAGES = ("mainos", "bootstrap", "hardware")


def load(path: Path) -> dict:
    with open(path, "rb") as fh:
        return tomllib.load(fh)


def flat(syms: dict) -> dict[str, tuple[int, str, str]]:
    """name -> (value, kind, status)."""
    out = {}
    for kind in KINDS:
        for name, entry in syms.get(kind, {}).items():
            image = entry.get("image", "mainos")
            if image not in IMAGES:
                raise ValueError(f"{name!r}: image must be one of {IMAGES}, got {image!r}")
            if image != "mainos":
                continue
            value = entry["addr"] if kind != "const" else entry["value"]
            if name in out:
                raise ValueError(f"duplicate symbol {name!r}")
            out[name] = (value, kind, entry.get("status", "unknown"))
    return out


def emit_inc(syms: dict, out_path: Path) -> int:
    """Write a GNU as include defining every symbol as an absolute .equ."""
    table = flat(syms)
    lines = [
        "| Generated by tools/symbols.py from re/symbols.toml - do not edit.",
        f"| target {syms['meta']['target']}",
        "",
    ]
    for name, (value, kind, status) in sorted(table.items(), key=lambda kv: kv[1][0]):
        lines.append(f"        .equ    {name}, 0x{value:08x}   | {kind}, {status}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    return len(table)


def emit_ghidra(syms: dict, out_path: Path) -> int:
    """Write a Ghidra script that names every symbol in a freshly imported project."""
    table = flat(syms)
    body = []
    for name, (value, kind, _status) in sorted(table.items(), key=lambda kv: kv[1][0]):
        if kind == "const":
            continue
        body.append(f'        name(0x{value:08x}L, "{name}", {str(kind == "fn").lower()});')
    src = f"""// Generated by tools/symbols.py from re/symbols.toml - do not edit.
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.symbol.SourceType;

public class ApplySymbols extends GhidraScript {{
    void name(long v, String n, boolean isFn) throws Exception {{
        Address a = currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(v);
        if (isFn) {{
            disassemble(a);
            Function f = getFunctionContaining(a);
            if (f == null) f = createFunction(a, n);
            if (f != null) {{ f.setName(n, SourceType.USER_DEFINED); return; }}
        }}
        createLabel(a, n, true);
    }}

    public void run() throws Exception {{
{chr(10).join(body)}
        println("applied {len(body)} symbols");
    }}
}}
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(src)
    return len(body)


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    s = load(root / "re" / "symbols.toml")
    n = emit_inc(s, root / "build" / "symbols.inc")
    m = emit_ghidra(s, root / "re" / "ghidra" / "scripts" / "ApplySymbols.java")
    print(f"symbols.inc: {n} symbols; ApplySymbols.java: {m} symbols")
